# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutDialogBA.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialogBA(object):
    def setupUi(self, AboutDialogBA):
        AboutDialogBA.setObjectName("AboutDialogBA")
        AboutDialogBA.resize(556, 384)
        AboutDialogBA.setSizeGripEnabled(True)
        AboutDialogBA.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(AboutDialogBA)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setSpacing(6)
        self.gridLayout1.setObjectName("gridLayout1")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelIcon = QtWidgets.QLabel(AboutDialogBA)
        self.labelIcon.setText("")
        self.labelIcon.setObjectName("labelIcon")
        self.horizontalLayout.addWidget(self.labelIcon)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setSpacing(6)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.label_kang = QtWidgets.QLabel(AboutDialogBA)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_kang.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        self.label_kang.setFont(font)
        self.label_kang.setObjectName("label_kang")
        self.verticalLayout1.addWidget(self.label_kang)
        self.label_outline = QtWidgets.QLabel(AboutDialogBA)
        self.label_outline.setObjectName("label_outline")
        self.verticalLayout1.addWidget(self.label_outline)
        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.label_fool1 = QtWidgets.QLabel(AboutDialogBA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fool1.sizePolicy().hasHeightForWidth())
        self.label_fool1.setSizePolicy(sizePolicy)
        self.label_fool1.setText("")
        self.label_fool1.setObjectName("label_fool1")
        self.horizontalLayout.addWidget(self.label_fool1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(AboutDialogBA)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout2.setSpacing(6)
        self.gridLayout2.setObjectName("gridLayout2")
        self.label_fool4 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fool4.sizePolicy().hasHeightForWidth())
        self.label_fool4.setSizePolicy(sizePolicy)
        self.label_fool4.setText("")
        self.label_fool4.setObjectName("label_fool4")
        self.gridLayout2.addWidget(self.label_fool4, 8, 2, 1, 1)
        self.label_fool5 = QtWidgets.QLabel(self.tab_1)
        self.label_fool5.setText("")
        self.label_fool5.setObjectName("label_fool5")
        self.gridLayout2.addWidget(self.label_fool5, 2, 0, 1, 1)
        self.label_licensetxt = QtWidgets.QLabel(self.tab_1)
        self.label_licensetxt.setObjectName("label_licensetxt")
        self.gridLayout2.addWidget(self.label_licensetxt, 4, 1, 1, 1)
        self.label_license = QtWidgets.QLabel(self.tab_1)
        self.label_license.setObjectName("label_license")
        self.gridLayout2.addWidget(self.label_license, 4, 0, 1, 1)
        self.label_homepage = QtWidgets.QLabel(self.tab_1)
        self.label_homepage.setObjectName("label_homepage")
        self.gridLayout2.addWidget(self.label_homepage, 3, 0, 1, 1)
        self.label_version = QtWidgets.QLabel(self.tab_1)
        self.label_version.setObjectName("label_version")
        self.gridLayout2.addWidget(self.label_version, 1, 0, 1, 1)
        self.label_versiontxt = QtWidgets.QLabel(self.tab_1)
        self.label_versiontxt.setObjectName("label_versiontxt")
        self.gridLayout2.addWidget(self.label_versiontxt, 1, 1, 1, 1)
        self.label_fool3 = QtWidgets.QLabel(self.tab_1)
        self.label_fool3.setText("")
        self.label_fool3.setObjectName("label_fool3")
        self.gridLayout2.addWidget(self.label_fool3, 8, 1, 1, 1)
        self.label_homepagetxt = QtWidgets.QLabel(self.tab_1)
        self.label_homepagetxt.setObjectName("label_homepagetxt")
        self.gridLayout2.addWidget(self.label_homepagetxt, 3, 1, 1, 1)
        self.label_fool6 = QtWidgets.QLabel(self.tab_1)
        self.label_fool6.setText("")
        self.label_fool6.setObjectName("label_fool6")
        self.gridLayout2.addWidget(self.label_fool6, 2, 1, 1, 1)
        self.label_fool2 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_fool2.sizePolicy().hasHeightForWidth())
        self.label_fool2.setSizePolicy(sizePolicy)
        self.label_fool2.setText("")
        self.label_fool2.setObjectName("label_fool2")
        self.gridLayout2.addWidget(self.label_fool2, 8, 0, 1, 1)
        self.label_fool7 = QtWidgets.QLabel(self.tab_1)
        self.label_fool7.setText("")
        self.label_fool7.setObjectName("label_fool7")
        self.gridLayout2.addWidget(self.label_fool7, 0, 0, 1, 1)
        self.label_fool8 = QtWidgets.QLabel(self.tab_1)
        self.label_fool8.setText("")
        self.label_fool8.setObjectName("label_fool8")
        self.gridLayout2.addWidget(self.label_fool8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout3.setSpacing(6)
        self.gridLayout3.setObjectName("gridLayout3")
        self.textAuthors = QtWidgets.QTextBrowser(self.tab_2)
        self.textAuthors.setReadOnly(True)
        self.textAuthors.setOpenExternalLinks(True)
        self.textAuthors.setOpenLinks(True)
        self.textAuthors.setObjectName("textAuthors")
        self.gridLayout3.addWidget(self.textAuthors, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout1.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout1, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutDialogBA)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(AboutDialogBA)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(AboutDialogBA.close)
        QtCore.QMetaObject.connectSlotsByName(AboutDialogBA)

    def retranslateUi(self, AboutDialogBA):
        _translate = QtCore.QCoreApplication.translate
        AboutDialogBA.setWindowTitle(_translate("AboutDialogBA", "About"))
        self.label_kang.setText(_translate("AboutDialogBA", "KANG"))
        self.label_outline.setText(_translate("AboutDialogBA", "The Python Regular Expression Editor"))
        self.label_licensetxt.setText(_translate("AboutDialogBA", "TextLabel"))
        self.label_license.setText(_translate("AboutDialogBA", "License:"))
        self.label_homepage.setText(_translate("AboutDialogBA", "Homepage:"))
        self.label_version.setText(_translate("AboutDialogBA", "Version:"))
        self.label_versiontxt.setText(_translate("AboutDialogBA", "TextLabel"))
        self.label_homepagetxt.setText(_translate("AboutDialogBA", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("AboutDialogBA", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AboutDialogBA", "Authors"))
