# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutBA4.ui'
#
# Created: Wed Jan 29 08:38:12 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AboutBA(object):
    def setupUi(self, AboutBA):
        AboutBA.setObjectName(_fromUtf8("AboutBA"))
        AboutBA.resize(474, 496)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        AboutBA.setPalette(palette)
        AboutBA.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(AboutBA)
        self.gridlayout.setMargin(11)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__ = QtGui.QGroupBox(AboutBA)
        self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__.setObjectName(_fromUtf8("GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__"))
        self.gridlayout1 = QtGui.QGridLayout(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.TextLabel1_2 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.TextLabel1_2.setWordWrap(False)
        self.TextLabel1_2.setObjectName(_fromUtf8("TextLabel1_2"))
        self.hboxlayout.addWidget(self.TextLabel1_2)
        self.versionLabel = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.versionLabel.setWordWrap(False)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.hboxlayout.addWidget(self.versionLabel)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 3, 1, 2)
        spacerItem = QtGui.QSpacerItem(181, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 0, 2, 1, 1)
        self.TextLabel1 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1.sizePolicy().hasHeightForWidth())
        self.TextLabel1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("helvetic"))
        self.TextLabel1.setFont(font)
        self.TextLabel1.setWordWrap(False)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.gridlayout1.addWidget(self.TextLabel1, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(26, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridlayout1.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(36, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 4, 0, 1, 1)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.textLabel3 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.vboxlayout.addWidget(self.textLabel3)
        self.textLabel4 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName(_fromUtf8("textLabel4"))
        self.vboxlayout.addWidget(self.textLabel4)
        self.gridlayout1.addLayout(self.vboxlayout, 1, 1, 2, 3)
        spacerItem3 = QtGui.QSpacerItem(40, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(35, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem4, 2, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(41, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(41, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem6, 2, 0, 1, 1)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.textLabel1 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridlayout2.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.textLabel2 = QtGui.QLabel(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.gridlayout2.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 4, 1, 2, 3)
        spacerItem7 = QtGui.QSpacerItem(70, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem7, 4, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(55, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem8, 5, 4, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(50, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem9, 5, 0, 1, 1)
        self.gridlayout.addWidget(self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__, 1, 0, 1, 1)
        self.PixmapLabel1 = QtGui.QLabel(AboutBA)
        self.PixmapLabel1.setPixmap(QtGui.QPixmap(_fromUtf8("image0")))
        self.PixmapLabel1.setScaledContents(True)
        self.PixmapLabel1.setWordWrap(False)
        self.PixmapLabel1.setObjectName(_fromUtf8("PixmapLabel1"))
        self.gridlayout.addWidget(self.PixmapLabel1, 0, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem10)
        self.buttonOk = QtGui.QPushButton(AboutBA)
        self.buttonOk.setAutoDefault(True)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName(_fromUtf8("buttonOk"))
        self.hboxlayout1.addWidget(self.buttonOk)
        self.gridlayout.addLayout(self.hboxlayout1, 2, 0, 1, 1)

        self.retranslateUi(AboutBA)
        QtCore.QObject.connect(self.buttonOk, QtCore.SIGNAL(_fromUtf8("clicked()")), AboutBA.accept)
        QtCore.QMetaObject.connectSlotsByName(AboutBA)

    def retranslateUi(self, AboutBA):
        AboutBA.setWindowTitle(_translate("AboutBA", "About Kodos", None))
        self.GroupBox6__DOCTYPE_UI_SELECTION__UI_SELECTION___widget_______class_QLabel__class_______property_stdset__1____________name_name__name___________cstring_TextLabel1_2__cstring________property_______property_stdset__1____________name_geometry__name___________rect_______________x_11__x_______________y_280__y_______________width_90__width_______________height_26__height____________rect________property_______property_stdset__1____________name_text__name___________string_Version___string________property____widget____UI_SELECTION__.setTitle(_translate("AboutBA", "About...", None))
        self.TextLabel1_2.setText(_translate("AboutBA", "Version:", None))
        self.versionLabel.setText(_translate("AboutBA", "0.8", None))
        self.TextLabel1.setText(_translate("AboutBA", "Kodos", None))
        self.textLabel3.setText(_translate("AboutBA", "Developed by: Phil Schwartz", None))
        self.textLabel4.setText(_translate("AboutBA", "phil_schwartz@users.sourceforge.net", None))
        self.textLabel1.setText(_translate("AboutBA", "Logo designed by: Konstantin Ryabitsev", None))
        self.textLabel2.setText(_translate("AboutBA", "icon@fedoraproject.org", None))
        self.buttonOk.setText(_translate("AboutBA", "&OK", None))


class AboutBA(QtGui.QDialog, Ui_AboutBA):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QDialog.__init__(self, parent, f)

        self.setupUi(self)

