# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kodosBA4.ui'
#
# Created: Thu Nov  7 15:43:26 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KodosBA(object):
    def setupUi(self, KodosBA):
        KodosBA.setObjectName(_fromUtf8("KodosBA"))
        KodosBA.resize(600, 713)
        self.widget = QtGui.QWidget(KodosBA)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridlayout = QtGui.QGridLayout(self.widget)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.groupBox2 = QtGui.QGroupBox(self.widget)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.buttonGroup2 = QtGui.QButtonGroup(self.groupBox2)
        self.buttonGroup2.setObjectName(_fromUtf8("buttonGroup2"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox2)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.ignorecaseCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.ignorecaseCheckBox.setObjectName(_fromUtf8("ignorecaseCheckBox"))
        self.hboxlayout.addWidget(self.ignorecaseCheckBox)
        self.multilineCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.multilineCheckBox.setObjectName(_fromUtf8("multilineCheckBox"))
        self.hboxlayout.addWidget(self.multilineCheckBox)
        self.dotallCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.dotallCheckBox.setObjectName(_fromUtf8("dotallCheckBox"))
        self.hboxlayout.addWidget(self.dotallCheckBox)
        self.verboseCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.verboseCheckBox.setObjectName(_fromUtf8("verboseCheckBox"))
        self.hboxlayout.addWidget(self.verboseCheckBox)
        self.localeCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.localeCheckBox.setObjectName(_fromUtf8("localeCheckBox"))
        self.hboxlayout.addWidget(self.localeCheckBox)
        self.unicodeCheckBox = QtGui.QCheckBox(self.groupBox2)
        self.unicodeCheckBox.setObjectName(_fromUtf8("unicodeCheckBox"))
        self.hboxlayout.addWidget(self.unicodeCheckBox)
        self.gridlayout.addWidget(self.groupBox2, 1, 0, 1, 1)
        self.groupBox1 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setProperty("lineWidth", 1)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox1)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.regexMultiLineEdit = QtGui.QTextEdit(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica [Adobe]"))
        self.regexMultiLineEdit.setFont(font)
        self.regexMultiLineEdit.setProperty("text", _fromUtf8(""))
        self.regexMultiLineEdit.setObjectName(_fromUtf8("regexMultiLineEdit"))
        self.gridlayout1.addWidget(self.regexMultiLineEdit, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.resultTabWidget = QtGui.QTabWidget(self.widget)
        self.resultTabWidget.setObjectName(_fromUtf8("resultTabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridlayout2 = QtGui.QGridLayout(self.tab)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.resultTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.gridlayout3 = QtGui.QGridLayout(self.tab1)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.matchTextBrowser = QtGui.QTextBrowser(self.tab1)
        self.matchTextBrowser.setObjectName(_fromUtf8("matchTextBrowser"))
        self.gridlayout3.addWidget(self.matchTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.tab1, _fromUtf8(""))
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName(_fromUtf8("TabPage"))
        self.gridlayout4 = QtGui.QGridLayout(self.TabPage)
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.matchAllTextBrowser = QtGui.QTextBrowser(self.TabPage)
        self.matchAllTextBrowser.setObjectName(_fromUtf8("matchAllTextBrowser"))
        self.gridlayout4.addWidget(self.matchAllTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage, _fromUtf8(""))
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName(_fromUtf8("TabPage1"))
        self.vboxlayout = QtGui.QVBoxLayout(self.TabPage1)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.replaceTextBrowser = QtGui.QTextBrowser(self.TabPage1)
        self.replaceTextBrowser.setObjectName(_fromUtf8("replaceTextBrowser"))
        self.vboxlayout.addWidget(self.replaceTextBrowser)
        self.resultTabWidget.addTab(self.TabPage1, _fromUtf8(""))
        self.TabPage2 = QtGui.QWidget()
        self.TabPage2.setObjectName(_fromUtf8("TabPage2"))
        self.gridlayout5 = QtGui.QGridLayout(self.TabPage2)
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        self.codeTextBrowser = QtGui.QTextBrowser(self.TabPage2)
        self.codeTextBrowser.setObjectName(_fromUtf8("codeTextBrowser"))
        self.gridlayout5.addWidget(self.codeTextBrowser, 0, 0, 1, 1)
        self.resultTabWidget.addTab(self.TabPage2, _fromUtf8(""))
        self.gridlayout.addWidget(self.resultTabWidget, 4, 0, 1, 1)
        self.tabWidget3 = QtGui.QTabWidget(self.widget)
        self.tabWidget3.setObjectName(_fromUtf8("tabWidget3"))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.gridlayout6 = QtGui.QGridLayout(self.tab2)
        self.gridlayout6.setObjectName(_fromUtf8("gridlayout6"))
        self.stringMultiLineEdit = QtGui.QTextEdit(self.tab2)
        self.stringMultiLineEdit.setObjectName(_fromUtf8("stringMultiLineEdit"))
        self.gridlayout6.addWidget(self.stringMultiLineEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.gridlayout7 = QtGui.QGridLayout(self.tab3)
        self.gridlayout7.setObjectName(_fromUtf8("gridlayout7"))
        self.replaceTextEdit = QtGui.QTextEdit(self.tab3)
        self.replaceTextEdit.setObjectName(_fromUtf8("replaceTextEdit"))
        self.gridlayout7.addWidget(self.replaceTextEdit, 0, 0, 1, 1)
        self.tabWidget3.addTab(self.tab3, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget3, 2, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem = QtGui.QSpacerItem(70, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.textLabel1 = QtGui.QLabel(self.widget)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.hboxlayout1.addWidget(self.textLabel1)
        self.matchNumberSpinBox = QtGui.QSpinBox(self.widget)
        self.matchNumberSpinBox.setMinimum(1)
        self.matchNumberSpinBox.setMaximum(9999)
        self.matchNumberSpinBox.setObjectName(_fromUtf8("matchNumberSpinBox"))
        self.hboxlayout1.addWidget(self.matchNumberSpinBox)
        self.spacerLabel = QtGui.QLabel(self.widget)
        self.spacerLabel.setPixmap(QtGui.QPixmap(_fromUtf8("image1")))
        self.spacerLabel.setWordWrap(False)
        self.spacerLabel.setObjectName(_fromUtf8("spacerLabel"))
        self.hboxlayout1.addWidget(self.spacerLabel)
        self.replaceLabel = QtGui.QLabel(self.widget)
        self.replaceLabel.setWordWrap(False)
        self.replaceLabel.setObjectName(_fromUtf8("replaceLabel"))
        self.hboxlayout1.addWidget(self.replaceLabel)
        self.replaceNumberSpinBox = QtGui.QSpinBox(self.widget)
        self.replaceNumberSpinBox.setObjectName(_fromUtf8("replaceNumberSpinBox"))
        self.hboxlayout1.addWidget(self.replaceNumberSpinBox)
        spacerItem1 = QtGui.QSpacerItem(118, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout.addLayout(self.hboxlayout1, 3, 0, 1, 1)
        KodosBA.setCentralWidget(self.widget)
        self.toolBar = QtGui.QToolBar(KodosBA)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        KodosBA.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(KodosBA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setObjectName(_fromUtf8("editMenu"))
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        KodosBA.setMenuBar(self.menubar)
        self.fileNewAction = QtGui.QAction(KodosBA)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image2")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileNewAction.setIcon(icon)
        self.fileNewAction.setProperty("name", _fromUtf8("fileNewAction"))
        self.fileNewAction.setObjectName(_fromUtf8("fileNewAction"))
        self.fileOpenAction = QtGui.QAction(KodosBA)
        self.fileOpenAction.setProperty("name", _fromUtf8("fileOpenAction"))
        self.fileOpenAction.setObjectName(_fromUtf8("fileOpenAction"))
        self.fileSaveAction = QtGui.QAction(KodosBA)
        self.fileSaveAction.setProperty("name", _fromUtf8("fileSaveAction"))
        self.fileSaveAction.setObjectName(_fromUtf8("fileSaveAction"))
        self.fileSaveAsAction = QtGui.QAction(KodosBA)
        self.fileSaveAsAction.setShortcut(_fromUtf8(""))
        self.fileSaveAsAction.setProperty("name", _fromUtf8("fileSaveAsAction"))
        self.fileSaveAsAction.setObjectName(_fromUtf8("fileSaveAsAction"))
        self.fileExitAction = QtGui.QAction(KodosBA)
        self.fileExitAction.setShortcut(_fromUtf8(""))
        self.fileExitAction.setProperty("name", _fromUtf8("fileExitAction"))
        self.fileExitAction.setObjectName(_fromUtf8("fileExitAction"))
        self.editUndoAction = QtGui.QAction(KodosBA)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("image5")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndoAction.setIcon(icon1)
        self.editUndoAction.setProperty("name", _fromUtf8("editUndoAction"))
        self.editUndoAction.setObjectName(_fromUtf8("editUndoAction"))
        self.editRedoAction = QtGui.QAction(KodosBA)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("image6")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRedoAction.setIcon(icon2)
        self.editRedoAction.setProperty("name", _fromUtf8("editRedoAction"))
        self.editRedoAction.setObjectName(_fromUtf8("editRedoAction"))
        self.editCutAction = QtGui.QAction(KodosBA)
        self.editCutAction.setProperty("name", _fromUtf8("editCutAction"))
        self.editCutAction.setObjectName(_fromUtf8("editCutAction"))
        self.editCopyAction = QtGui.QAction(KodosBA)
        self.editCopyAction.setProperty("name", _fromUtf8("editCopyAction"))
        self.editCopyAction.setObjectName(_fromUtf8("editCopyAction"))
        self.editPasteAction = QtGui.QAction(KodosBA)
        self.editPasteAction.setProperty("name", _fromUtf8("editPasteAction"))
        self.editPasteAction.setObjectName(_fromUtf8("editPasteAction"))
        self.examineAction = QtGui.QAction(KodosBA)
        self.examineAction.setCheckable(True)
        self.examineAction.setProperty("name", _fromUtf8("examineAction"))
        self.examineAction.setObjectName(_fromUtf8("examineAction"))
        self.helpAboutAction = QtGui.QAction(KodosBA)
        self.helpAboutAction.setShortcut(_fromUtf8(""))
        self.helpAboutAction.setProperty("name", _fromUtf8("helpAboutAction"))
        self.helpAboutAction.setObjectName(_fromUtf8("helpAboutAction"))
        self.regexChangedAction = QtGui.QAction(KodosBA)
        self.regexChangedAction.setProperty("name", _fromUtf8("regexChangedAction"))
        self.regexChangedAction.setObjectName(_fromUtf8("regexChangedAction"))
        self.editPauseAction = QtGui.QAction(KodosBA)
        self.editPauseAction.setCheckable(True)
        self.editPauseAction.setProperty("name", _fromUtf8("editPauseAction"))
        self.editPauseAction.setObjectName(_fromUtf8("editPauseAction"))
        self.editPreferencesAction = QtGui.QAction(KodosBA)
        self.editPreferencesAction.setProperty("name", _fromUtf8("editPreferencesAction"))
        self.editPreferencesAction.setObjectName(_fromUtf8("editPreferencesAction"))
        self.helpHelpAction = QtGui.QAction(KodosBA)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("image12")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpHelpAction.setIcon(icon3)
        self.helpHelpAction.setProperty("name", _fromUtf8("helpHelpAction"))
        self.helpHelpAction.setObjectName(_fromUtf8("helpHelpAction"))
        self.helpPythonHelpAction = QtGui.QAction(KodosBA)
        self.helpPythonHelpAction.setProperty("name", _fromUtf8("helpPythonHelpAction"))
        self.helpPythonHelpAction.setObjectName(_fromUtf8("helpPythonHelpAction"))
        self.helpRegexReferenceAction = QtGui.QAction(KodosBA)
        self.helpRegexReferenceAction.setProperty("name", _fromUtf8("helpRegexReferenceAction"))
        self.helpRegexReferenceAction.setObjectName(_fromUtf8("helpRegexReferenceAction"))
        self.helpVisitWebsiteAction = QtGui.QAction(KodosBA)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("image14")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpVisitWebsiteAction.setIcon(icon4)
        self.helpVisitWebsiteAction.setProperty("name", _fromUtf8("helpVisitWebsiteAction"))
        self.helpVisitWebsiteAction.setObjectName(_fromUtf8("helpVisitWebsiteAction"))
        self.helpCheckForUpdateAction = QtGui.QAction(KodosBA)
        self.helpCheckForUpdateAction.setProperty("name", _fromUtf8("helpCheckForUpdateAction"))
        self.helpCheckForUpdateAction.setObjectName(_fromUtf8("helpCheckForUpdateAction"))
        self.helpReportBugAction = QtGui.QAction(KodosBA)
        self.helpReportBugAction.setProperty("name", _fromUtf8("helpReportBugAction"))
        self.helpReportBugAction.setObjectName(_fromUtf8("helpReportBugAction"))
        self.noopAction = QtGui.QAction(KodosBA)
        self.noopAction.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("image15")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noopAction.setIcon(icon5)
        self.noopAction.setText(_fromUtf8(""))
        self.noopAction.setIconText(_fromUtf8(""))
        self.noopAction.setProperty("name", _fromUtf8("noopAction"))
        self.noopAction.setObjectName(_fromUtf8("noopAction"))
        self.fileImportFileAction = QtGui.QAction(KodosBA)
        self.fileImportFileAction.setProperty("name", _fromUtf8("fileImportFileAction"))
        self.fileImportFileAction.setObjectName(_fromUtf8("fileImportFileAction"))
        self.fileImportURLAction = QtGui.QAction(KodosBA)
        self.fileImportURLAction.setProperty("name", _fromUtf8("fileImportURLAction"))
        self.fileImportURLAction.setObjectName(_fromUtf8("fileImportURLAction"))
        self.helpRegexLibAction = QtGui.QAction(KodosBA)
        self.helpRegexLibAction.setProperty("name", _fromUtf8("helpRegexLibAction"))
        self.helpRegexLibAction.setObjectName(_fromUtf8("helpRegexLibAction"))
        self.FileRevertAction = QtGui.QAction(KodosBA)
        self.FileRevertAction.setProperty("name", _fromUtf8("FileRevertAction"))
        self.FileRevertAction.setObjectName(_fromUtf8("FileRevertAction"))
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileSaveAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editCutAction)
        self.toolBar.addAction(self.editCopyAction)
        self.toolBar.addAction(self.editPasteAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editPauseAction)
        self.toolBar.addAction(self.examineAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.helpRegexReferenceAction)
        self.toolBar.addAction(self.helpRegexLibAction)
        self.fileMenu.addAction(self.fileNewAction)
        self.fileMenu.addAction(self.fileOpenAction)
        self.fileMenu.addAction(self.fileSaveAction)
        self.fileMenu.addAction(self.fileSaveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.FileRevertAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileImportFileAction)
        self.fileMenu.addAction(self.fileImportURLAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.fileMenu.addSeparator()
        self.editMenu.addAction(self.editUndoAction)
        self.editMenu.addAction(self.editRedoAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editCutAction)
        self.editMenu.addAction(self.editCopyAction)
        self.editMenu.addAction(self.editPasteAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.examineAction)
        self.editMenu.addAction(self.editPauseAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editPreferencesAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpHelpAction)
        self.helpMenu.addAction(self.helpPythonHelpAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpRegexReferenceAction)
        self.helpMenu.addAction(self.helpRegexLibAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpVisitWebsiteAction)
        self.helpMenu.addAction(self.helpCheckForUpdateAction)
        self.helpMenu.addAction(self.helpReportBugAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.helpAboutAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(KodosBA)
        self.resultTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dotallCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.editCopyAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.editCopy)
        QtCore.QObject.connect(self.editCutAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.editCut)
        QtCore.QObject.connect(self.editPasteAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.editPaste)
        QtCore.QObject.connect(self.editRedoAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.editRedo)
        QtCore.QObject.connect(self.editUndoAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.editUndo)
        QtCore.QObject.connect(self.examineAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.examine)
        QtCore.QObject.connect(self.fileExitAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.close)
        QtCore.QObject.connect(self.fileNewAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.fileNew)
        QtCore.QObject.connect(self.fileOpenAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.fileOpen)
        QtCore.QObject.connect(self.fileSaveAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.fileSave)
        QtCore.QObject.connect(self.fileSaveAsAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.fileSaveAs)
        QtCore.QObject.connect(self.helpAboutAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.helpAbout)
        QtCore.QObject.connect(self.helpHelpAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.helpHelp)
        QtCore.QObject.connect(self.ignorecaseCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.localeCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.matchNumberSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), KodosBA.match_num_slot)
        QtCore.QObject.connect(self.multilineCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.regexMultiLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.regex_changed_slot)
        QtCore.QObject.connect(self.stringMultiLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.string_changed_slot)
        QtCore.QObject.connect(self.unicodeCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.verboseCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.checkbox_slot)
        QtCore.QObject.connect(self.editPauseAction, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.pause)
        QtCore.QObject.connect(self.editPreferencesAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.preferences)
        QtCore.QObject.connect(self.helpReportBugAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.report_bug)
        QtCore.QObject.connect(self.helpPythonHelpAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.helpPythonRegex)
        QtCore.QObject.connect(self.helpRegexReferenceAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.reference_guide)
        QtCore.QObject.connect(self.helpVisitWebsiteAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.kodos_website)
        QtCore.QObject.connect(self.helpCheckForUpdateAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.check_for_update)
        QtCore.QObject.connect(self.replaceTextEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.replace_changed_slot)
        QtCore.QObject.connect(self.replaceNumberSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), KodosBA.replace_num_slot)
        QtCore.QObject.connect(self.fileImportFileAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.importFile)
        QtCore.QObject.connect(self.fileImportURLAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.importURL)
        QtCore.QObject.connect(self.helpRegexLibAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.helpRegexLib)
        QtCore.QObject.connect(self.regexMultiLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.stringMultiLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.ignorecaseCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.replaceTextEdit, QtCore.SIGNAL(_fromUtf8("textChanged()")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.multilineCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.dotallCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.verboseCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.localeCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.unicodeCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), KodosBA.kodos_edited_slot)
        QtCore.QObject.connect(self.FileRevertAction, QtCore.SIGNAL(_fromUtf8("activated()")), KodosBA.revert_file_slot)
        QtCore.QMetaObject.connectSlotsByName(KodosBA)
        KodosBA.setTabOrder(self.regexMultiLineEdit, self.stringMultiLineEdit)
        KodosBA.setTabOrder(self.stringMultiLineEdit, self.resultTabWidget)
        KodosBA.setTabOrder(self.resultTabWidget, self.ignorecaseCheckBox)
        KodosBA.setTabOrder(self.ignorecaseCheckBox, self.multilineCheckBox)
        KodosBA.setTabOrder(self.multilineCheckBox, self.dotallCheckBox)
        KodosBA.setTabOrder(self.dotallCheckBox, self.verboseCheckBox)
        KodosBA.setTabOrder(self.verboseCheckBox, self.localeCheckBox)
        KodosBA.setTabOrder(self.localeCheckBox, self.unicodeCheckBox)
        KodosBA.setTabOrder(self.unicodeCheckBox, self.matchNumberSpinBox)
        KodosBA.setTabOrder(self.matchNumberSpinBox, self.matchTextBrowser)
        KodosBA.setTabOrder(self.matchTextBrowser, self.codeTextBrowser)

    def retranslateUi(self, KodosBA):
        KodosBA.setWindowTitle(_translate("KodosBA", "Kodos - The Python Regex Debugger", None))
        KodosBA.setWindowIconText(_translate("KodosBA", "Kodos", None))
        self.groupBox2.setTitle(_translate("KodosBA", "Flags", None))
        self.ignorecaseCheckBox.setToolTip(_translate("KodosBA", "Perform case-insensitive matching; expressions like [A-Z] will match\n"
"lowercase letters, too. This is not affected by the current locale.", None))
        self.ignorecaseCheckBox.setText(_translate("KodosBA", "Ignore Case", None))
        self.multilineCheckBox.setToolTip(_translate("KodosBA", "When specified, the pattern character \"^\" matches at the beginning of the \n"
"string and at the beginning of each line (immediately following each newline); \n"
"and the pattern character \"$\" matches at the end of the string and at the end \n"
"of each line (immediately preceding each newline). By default, \"^\" matches \n"
"only at the beginning of the string, and \"$\" only at the end of the string and \n"
"immediately before the newline (if any) at the end of the string.", None))
        self.multilineCheckBox.setText(_translate("KodosBA", "Multi Line", None))
        self.dotallCheckBox.setToolTip(_translate("KodosBA", "Make the \".\" special character match any character at all, including a \n"
"newline; without this flag, \".\" will match anything except a newline.", None))
        self.dotallCheckBox.setText(_translate("KodosBA", "Dot All", None))
        self.verboseCheckBox.setToolTip(_translate("KodosBA", "This flag allows you to write regular expressions that look nicer. Whitespace \n"
"within the pattern is ignored, except when in a character class or preceded by \n"
"an unescaped backslash, and, when a line contains a \"#\" neither in a character\n"
"class or preceded by an unescaped backslash, all characters from the leftmost \n"
"such \"#\" through the end of the line are ignored.", None))
        self.verboseCheckBox.setText(_translate("KodosBA", "Verbose", None))
        self.localeCheckBox.setToolTip(_translate("KodosBA", "Make \\w, \\W, \\b, and \\B dependent on the current locale.", None))
        self.localeCheckBox.setText(_translate("KodosBA", "Locale", None))
        self.unicodeCheckBox.setToolTip(_translate("KodosBA", "\"Make \\w, \\W, \\b, and \\B dependent on the Unicode character properties \n"
"database. New in Python version 2.0.", None))
        self.unicodeCheckBox.setText(_translate("KodosBA", "Unicode", None))
        self.groupBox1.setTitle(_translate("KodosBA", "Regular Expression Pattern", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab), _translate("KodosBA", "Group", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.tab1), _translate("KodosBA", "Match", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage), _translate("KodosBA", "Match All", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage1), _translate("KodosBA", "Replace", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.TabPage2), _translate("KodosBA", "Sample Code", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab2), _translate("KodosBA", "Search String", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab3), _translate("KodosBA", "Replace String", None))
        self.textLabel1.setText(_translate("KodosBA", "Match Number", None))
        self.replaceLabel.setText(_translate("KodosBA", "Replace Number", None))
        self.toolBar.setProperty("label", _translate("KodosBA", "Tools", None))
        self.fileMenu.setTitle(_translate("KodosBA", "&File", None))
        self.editMenu.setTitle(_translate("KodosBA", "&Edit", None))
        self.helpMenu.setTitle(_translate("KodosBA", "&Help", None))
        self.fileNewAction.setText(_translate("KodosBA", "&New", None))
        self.fileNewAction.setIconText(_translate("KodosBA", "New", None))
        self.fileNewAction.setShortcut(_translate("KodosBA", "Ctrl+N", None))
        self.fileOpenAction.setText(_translate("KodosBA", "&Open...", None))
        self.fileOpenAction.setIconText(_translate("KodosBA", "Open", None))
        self.fileOpenAction.setShortcut(_translate("KodosBA", "Ctrl+O", None))
        self.fileSaveAction.setText(_translate("KodosBA", "&Save", None))
        self.fileSaveAction.setIconText(_translate("KodosBA", "Save", None))
        self.fileSaveAction.setShortcut(_translate("KodosBA", "Ctrl+S", None))
        self.fileSaveAsAction.setText(_translate("KodosBA", "Save &As...", None))
        self.fileSaveAsAction.setIconText(_translate("KodosBA", "Save As", None))
        self.fileExitAction.setText(_translate("KodosBA", "E&xit", None))
        self.fileExitAction.setIconText(_translate("KodosBA", "Exit", None))
        self.editUndoAction.setText(_translate("KodosBA", "&Undo", None))
        self.editUndoAction.setIconText(_translate("KodosBA", "Undo", None))
        self.editUndoAction.setShortcut(_translate("KodosBA", "Ctrl+Z", None))
        self.editRedoAction.setText(_translate("KodosBA", "&Redo", None))
        self.editRedoAction.setIconText(_translate("KodosBA", "Redo", None))
        self.editRedoAction.setShortcut(_translate("KodosBA", "Ctrl+Y", None))
        self.editCutAction.setText(_translate("KodosBA", "&Cut", None))
        self.editCutAction.setIconText(_translate("KodosBA", "Cut", None))
        self.editCutAction.setShortcut(_translate("KodosBA", "Ctrl+X", None))
        self.editCopyAction.setText(_translate("KodosBA", "C&opy", None))
        self.editCopyAction.setIconText(_translate("KodosBA", "Copy", None))
        self.editCopyAction.setShortcut(_translate("KodosBA", "Ctrl+C", None))
        self.editPasteAction.setText(_translate("KodosBA", "&Paste", None))
        self.editPasteAction.setIconText(_translate("KodosBA", "Paste", None))
        self.editPasteAction.setShortcut(_translate("KodosBA", "Ctrl+V", None))
        self.examineAction.setText(_translate("KodosBA", "E&xamine Regex", None))
        self.examineAction.setIconText(_translate("KodosBA", "Examine Regex for Match", None))
        self.examineAction.setShortcut(_translate("KodosBA", "Ctrl+X", None))
        self.helpAboutAction.setText(_translate("KodosBA", "&About", None))
        self.helpAboutAction.setIconText(_translate("KodosBA", "About", None))
        self.regexChangedAction.setText(_translate("KodosBA", "Action", None))
        self.regexChangedAction.setIconText(_translate("KodosBA", "Action", None))
        self.editPauseAction.setText(_translate("KodosBA", "Pause Processing", None))
        self.editPauseAction.setIconText(_translate("KodosBA", "Pause Processing", None))
        self.editPauseAction.setShortcut(_translate("KodosBA", "Ctrl+P", None))
        self.editPreferencesAction.setText(_translate("KodosBA", "Preferences", None))
        self.editPreferencesAction.setIconText(_translate("KodosBA", "Preferences", None))
        self.helpHelpAction.setText(_translate("KodosBA", "Help", None))
        self.helpHelpAction.setIconText(_translate("KodosBA", "Help", None))
        self.helpHelpAction.setShortcut(_translate("KodosBA", "Ctrl+/", None))
        self.helpPythonHelpAction.setText(_translate("KodosBA", "&Python Regex Help", None))
        self.helpPythonHelpAction.setIconText(_translate("KodosBA", "Python Regex Help", None))
        self.helpRegexReferenceAction.setText(_translate("KodosBA", "&Regex Reference Guide", None))
        self.helpRegexReferenceAction.setIconText(_translate("KodosBA", "Regex Reference Guide", None))
        self.helpRegexReferenceAction.setShortcut(_translate("KodosBA", "Ctrl+R", None))
        self.helpVisitWebsiteAction.setText(_translate("KodosBA", "&Visit Kodos Website", None))
        self.helpVisitWebsiteAction.setIconText(_translate("KodosBA", "&Visit Kodos Website", None))
        self.helpCheckForUpdateAction.setText(_translate("KodosBA", "&Check for Kodos Update", None))
        self.helpCheckForUpdateAction.setIconText(_translate("KodosBA", "Check for Kodos Update", None))
        self.helpReportBugAction.setText(_translate("KodosBA", "Report a &Bug", None))
        self.helpReportBugAction.setIconText(_translate("KodosBA", "Report a Bug", None))
        self.fileImportFileAction.setText(_translate("KodosBA", "Import &File", None))
        self.fileImportFileAction.setIconText(_translate("KodosBA", "Import File", None))
        self.fileImportURLAction.setText(_translate("KodosBA", "Import &URL", None))
        self.fileImportURLAction.setIconText(_translate("KodosBA", "Import URL", None))
        self.helpRegexLibAction.setText(_translate("KodosBA", "Regex &Library", None))
        self.helpRegexLibAction.setIconText(_translate("KodosBA", "Regex Library", None))
        self.helpRegexLibAction.setToolTip(_translate("KodosBA", "Open the Regex Library", None))
        self.helpRegexLibAction.setShortcut(_translate("KodosBA", "Ctrl+L", None))
        self.FileRevertAction.setText(_translate("KodosBA", "&Revert Kodos File", None))
        self.FileRevertAction.setIconText(_translate("KodosBA", "Revert Kodos File", None))


class KodosBA(QtGui.QMainWindow, Ui_KodosBA):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

